# Generated by Django 5.2 on 2025-04-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='couverture',
        ),
    ]
