# Generated by Django 5.2 on 2025-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_morceau_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='morceaux_images/'),
        ),
    ]
